[package]
authors = ["dyk <359743984@qq.com>"]
edition = "2018"
name = "ihosts"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33.3"
ignore = "0.4.17"
prettytable-rs = "^0.8"
